# Settings for compiling balsam camera architecture

# Localized KCONFIG settings
# External Dependencies
CONFIG_SPECTRA_ISP=y
CONFIG_SPECTRA_ICP=y
CONFIG_SPECTRA_JPEG=y
CONFIG_SPECTRA_SENSOR=y
CONFIG_INTERCONNECT_QCOM=y
CONFIG_CAM_KTHREAD_WORKER=y
CONFIG_MSM_GLOBAL_SYNX_V2=y
CONFIG_SPECTRA_LLCC_STALING=y
CONFIG_SPECTRA_POWER_DOMAIN_SET_HW_MODE=y


ccflags-y += -DCONFIG_SPECTRA_ISP=1
ccflags-y += -DCONFIG_SPECTRA_ICP=1
ccflags-y += -DCONFIG_SPECTRA_JPEG=1
ccflags-y += -DCONFIG_SPECTRA_SENSOR=1
ccflags-y += -DCONFIG_MSM_GLOBAL_SYNX_V2=1

ccflags-y += -DCONFIG_INTERCONNECT_QCOM=1
ccflags-y += -DCONFIG_CAM_KTHREAD_WORKER=1
ccflags-y += -DCONFIG_SPECTRA_LLCC_STALING=1
ccflags-y += -DCONFIG_SPECTRA_POWER_DOMAIN_SET_HW_MODE=1
